### ISSUE TITLE
error: 'width' cannot be used as a function

### ISSUE THREAD

**Issue by j53y** [laura240406/SH1106#1]
```cpp
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp:111:1: error: no declaration matches 'SH1106::SH1106(int8_t)'
 SH1106::SH1106(int8_t reset) : Adafruit_GFX(SH1106_LCDWIDTH, SH1106_LCDHEIGHT) {}
 ^~~~~~
In file included from c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp:6:
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.h:65:7: note: candidates are: 'constexpr SH1106::SH1106(SH1106&&)'
 class SH1106 : public Adafruit_GFX {
       ^~~~~~
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.h:65:7: note:                 'constexpr SH1106::SH1106(const SH1106&)'
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.h:67:5: note:                 'SH1106::SH1106()'
     SH1106();
     ^~~~~~
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.h:65:7: note: 'class SH1106' defined here
 class SH1106 : public Adafruit_GFX {
       ^~~~~~
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp: In member function 'void SH1106::display()':
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp:271:26: error: 'height' cannot be used as a function
     byte height = height();
                          ^
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp:272:24: error: 'width' cannot be used as a function
     byte width = width();
                        ^
```

i keep getting this error no matter what, and i can't seem to fix it.

**Comment by laura240406** [comment]
I think this should be fixed now and the Arduino indexer will pick up the new version in a few hours and show the new 2.0.0 version.

**Comment by j53y** [comment]
less errors, but i still get this one:

```cpp
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp: In member function 'void SH1106::display()':
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp:271:26: error: 'height' cannot be used as a function
     byte height = height();
                          ^
c:\Users\Gebruiker\OneDrive\Documenten\Arduino\libraries\SH1106\SH1106.cpp:272:24: error: 'width' cannot be used as a function
     byte width = width();
                        ^
```

i updated the library, restarted the Arduino IDE but it still didn't fix it.

**Comment by anak1nelo** [comment]
I am having the same issue

**Comment by j53y** [comment]
> I think this should be fixed now and the Arduino indexer will pick up the new version in a few hours and show the new 2.0.0 version.

It's been a week and even the testdisplay example wont even flash.

**Comment by j53y** [comment]
> > I think this should be fixed now and the Arduino indexer will pick up the new version in a few hours and show the new 2.0.0 version.
> 
> It's been a week and even the testdisplay example wont even flash.

I updated my esp32 boards and now it suddenly works. Thx anyways!

**Comment by j53y** [comment]
Seems like whenever I do it in a new file I get the same error, but in the testdisplay it works (with my own code). I think that this is because the SH1106.cpp and SH1106.h are opened in the Arduino IDE while in testdisplay.ino.

**Comment by anak1nelo** [comment]
Yeah, really was wondering how you managed to make it work... Still an issue for me, waiting for an update.. hopefully..

**Comment by citadel2814** [comment]
I also have the same issue. Loaded up the example and it won't build. 

```
c:\Users\XXXX\Documents\Arduino\libraries\SH1106-2.0.0\SH1106.cpp: In member function 'void SH1106::display()':
c:\Users\harveyw\Documents\Arduino\libraries\SH1106-2.0.0\SH1106.cpp:271:26: error: 'height' cannot be used as a function
     byte height = height();
                          ^
c:\Users\XXXX\Documents\Arduino\libraries\SH1106-2.0.0\SH1106.cpp:272:24: error: 'width' cannot be used as a function
     byte width = width();
                        ^
```

**Comment by j53y** [comment]
> I also have the same issue. Loaded up the example and it won't build. 
> 
> ```
> c:\Users\XXXX\Documents\Arduino\libraries\SH1106-2.0.0\SH1106.cpp: In member function 'void SH1106::display()':
> c:\Users\harveyw\Documents\Arduino\libraries\SH1106-2.0.0\SH1106.cpp:271:26: error: 'height' cannot be used as a function
>      byte height = height();
>                           ^
> c:\Users\XXXX\Documents\Arduino\libraries\SH1106-2.0.0\SH1106.cpp:272:24: error: 'width' cannot be used as a function
>      byte width = width();
>                         ^
> ```

I found a better library: u8g2, just use that, compiles faster, and is easy to code.

**Comment by rsholmes** [comment]
I still have this issue. Apparently testdisplay.ino has the corrected library included in its folder, but the version you get with the library manager is still the old version.

One thing I notice is that apparently the version number in the library.properties file was not changed when the width/height problem was fixed. Is that why the library manager hasn't picked up the new version?

_Added:_ Well, maybe not — looks like the version number was updated at the same time as the width/height fix. But the library manager is serving up the older version of the code, even though it says the version is 2.0.0.
